IF
Detect([PC])
Global("Once","LOCALS",0)
THEN
RESPONSE #100
SetInterrupt(FALSE)
DisplayStringHead(Myself,@184)
Wait(1)
ForceSpell(LastSeenBy(Myself),PSIONIC_EGOWHIP)
SetInterrupt(TRUE)
SetGlobal("Once","LOCALS",1)
END

IF
HitBy([ANYONE],CRUSHING)
Global("firstspawn","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("firstspawn","LOCALS",1)
CreateVisualEffect("SPROTECT",[728.711])
CreateCreature("Stogolb",[728.711],E)
CreateVisualEffect("SPROTECT",[501.905])
CreateCreature("stogolb",[501.905],E)
END  