IF
Detect([PC])
Global("Once","LOCALS",0)
THEN
RESPONSE #100
SetInterrupt(FALSE)
DisplayStringHead(Myself,@184)
Wait(1)
ForceSpell(LastSeenBy(Myself),PSIONIC_EGOWHIP)
SetInterrupt(TRUE)
SetGlobal("Once","LOCALS",1)
END

IF
HitBy([ANYONE],CRUSHING)
Global("firstspawn","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("firstspawn","LOCALS",1)
CreateVisualEffect("SPROTECT",[1872.660])
CreateCreature("Stogolb",[1872.660],10)
CreateVisualEffect("SPROTECT",[501.905])
CreateCreature("stogolb",[2157.748],3)
END